name: Deploy datoteka

on:
  workflow_run:
    workflows: ["Testiranje"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
    - name: Kloniraj repozitorij
      uses: actions/checkout@v4

    - name: Prijava v DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker build
      run: docker build -t janmilosic/ORV-DetekcijaObraza:latest .

    - name: Docker push
      run: docker push janmilosic/ORV-DetekcijaObraza:latest