name: Testiranje

# Proži se ob vsakem pushu na git
on:
  push:
    branches: [ "main" ]

# Uporabimo self-hosted runnerja
jobs:
  preveri_teste:
    name: Preveri teste
    runs-on: self-hosted

    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v4

      - name: Ali datoteka test obstaja # Preverjanje ali test datoteka obstaja
        run: |
          if ls src/test_*.py 1> /dev/null 2>&1; then
            echo "Testi obstajajo"
          else
            echo "Testi ne obstajajo" > napaka.txt
            exit 1
          fi

      # Shranjevanje artefakta ob napaki
      - name: Shrani napako
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: napaka
          path: napaka.txt

  testiranje:
    name: Testiranje naloge
    runs-on: self-hosted
    needs: preveri_teste # Ta posel izvedemo, le ko preveri_teste uspe
    strategy:
      matrix:
        python-version: [ "3.8", "3.10" ] # Uporaba dveh različic Pythona

    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v4

      - name: Nastavi Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} # Nastavi verzijo iz matrike

      - name: Namesti odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pozeni teste
        run: |
          pytest || (echo "Napaka pri testih." > napaka.txt && exit 1)

      - name: Shranjevanje napake
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-napaka # Artifakt za napake
          path: napaka.txt