name: Deploy datoteka

# Skripa se zažene le če je Testiranje uspešno zaključeno
on:
  workflow_run:
    workflows: ["Testiranje"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
    - name: Kloniraj repozitorij
      uses: actions/checkout@v4

    # Varna privaja v docker z uporabo secrets
    - name: Prijava v DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker build
      run: docker build -t janmilosic/orv-detekcijaobraza:latest . # Zgradi sliko

    - name: Docker push
      run: docker push janmilosic/orv-detekcijaobraza:latest # Potisne sliko na DockerHub